services:
  next:
    image: ghcr.io/ebuaa/next-cda25/next:latest
    build:
      context: .
      target: next
    environment:
      - APP_ENV=dev
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]
    volumes:
      - ".:/app"