on:
  push:
    branches:
      - '**'
    tags:
      - 'v**'

jobs:
  gitleaks:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - run: npm audit --audit-level=high --omit=dev

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - run: npm ci
      - run: npm run build
      - name: Sauvegarde du cache
        uses: actions/cache/save@v4
        with:
          path: |
            node_modules
            .next
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-node2-${{ hashFiles('**/package-lock.json') }}

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Récupération du cache
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
            .next
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-node2-${{ hashFiles('**/package-lock.json') }}
          fail-on-cache-miss: 'true'
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        browser: [chrome, edge]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Récupération du cache
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
            .next
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-node2-${{ hashFiles('**/package-lock.json') }}
      - uses: cypress-io/github-action@v6
        with:
          install: false
          start: npm run start
          browser: ${{ matrix.browser }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos-${{ matrix.browser }}
          path: cypress/videos
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots-${{ matrix.browser }}
          path: cypress/screenshots

  deploy-dev:
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Configuration de la clé SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Déploiement en développement
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            export NVM_DIR="$HOME/.nvm"
            . "$NVM_DIR/nvm.sh"
            cd recette
            git fetch --all
            git reset --hard origin/dev
            npm install
            npm run build
            pm2 restart next-recette
          EOF

  deploy-prod:
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Configuration de la clé SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Déploiement en production
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            export NVM_DIR="$HOME/.nvm"
            . "$NVM_DIR/nvm.sh"
            cd next-cda25
            git fetch --all
            git reset --hard origin/main
            npm install
            npm run build
            pm2 restart next-app
          EOF
